### ISSUE TITLE
Error writing output files

### ISSUE THREAD

**Issue by stephenrdoyle** [DRL/kinfin#35]
Hi, 

I am getting an error that I am having trouble solving. 

I am using Orthofinder output as input to Kinfin with the following command.

kinfin \
--cluster_file Orthogroups.txt \
--config_file config.txt \
--sequence_ids_file SequenceIDs.txt \
--fasta_dir PROTEIN_FASTAs \
--species_ids_file SpeciesIDs.txt \
--tree_file SpeciesTree_rooted.txt

It seems to run fine, until it fails as it is writing the Kinfin output. The test dataset completes successfully, so the install seems to be ok. Presumably something with my input data, although Orthofinder completes successfully. I have tried reformatting the data a few different ways, but with little success.

Any thoughts would be greatly appreciated.

Best
Steve

[STATUS] - Plotting /kinfin_results/cluster_size_distribution.pdf
Traceback (most recent call last):
  File "/nfs/users/nfs_s/sd21/lustre118_link/software/POPGEN/kinfin/src/kinfin.py", line 2321, in <module>
    dataFactory.write_output()
  File "/nfs/users/nfs_s/sd21/lustre118_link/software/POPGEN/kinfin/src/kinfin.py", line 668, in write_output
    self.write_cluster_metrics()
  File "/nfs/users/nfs_s/sd21/lustre118_link/software/POPGEN/kinfin/src/kinfin.py", line 947, in write_cluster_metrics
    cluster_metrics_line.append(clusterObj.protein_length_stats['mean'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by stephenrdoyle** [comment]
All good, problem solved. 

Great tool BTW. 

Cheers, 
Steve
