### ISSUE TITLE
plot_cluster_size_distribution.py

### ISSUE THREAD

**Issue by Yixiangzhang1996** [DRL/kinfin#36]
`[+] Start ...
[+] Plotting "loglogpowerlaw" ...
Traceback (most recent call last):
  File "/home1/zyx/my_kinfin/kinfin-1.0.3/scripts/plot_cluster_size_distribution.py", line 237, in <module>
    dataObj.plot_cluster_sizes('loglogpowerlaw')
  File "/home1/zyx/my_kinfin/kinfin-1.0.3/scripts/plot_cluster_size_distribution.py", line 139, in plot_cluster_sizes
    ax.fill_between(x, y, y_bottom, facecolor=colour, interpolate = True, where = mask)
  File "/home1/zyx/.conda/envs/python27/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/home1/zyx/.conda/envs/python27/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5106, in fill_between
    map(np.ma.getmask, [x, y1, y2]))
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'`

**Comment by jcerca** [comment]
Hi Yixiangzhang1996,

running on the same error and haven't been able to solve it. Did you manage to solve it (before I ask Dom)?

Thank you in advance.
José
