### ISSUE TITLE
meet problem on "no attribute '__getitem__'"

### ISSUE THREAD

**Issue by HiHansChen** [DRL/kinfin#39]
Hi there,
I am trying to analyze my orthofinder output data with kinfin, I have encountered the following problem:
```
[STATUS] - Parsing /home/bmb/pecanGenome/orthofinder/kinfin/Orthogroups.txt ... this may take a while
[STATUS] - Output directories in
	/home/bmb/pecanGenome/orthofinder/kinfin/kinfin_results
[STATUS] - Directory exists. Deleting directory ...
[STATUS] - Creating directories ...
	/home/bmb/pecanGenome/orthofinder/kinfin/kinfin_results/all
	/home/bmb/pecanGenome/orthofinder/kinfin/kinfin_results/TAXON
[STATUS]	 - Clusters found = 250073
[STATUS] - Analysing clusters ...
[PROGRESS] 	- 100%
[STATUS] - Took 191.332006931s to analyse clusters
[STATUS] - Generating rarefaction data ...
[STATUS]	- Plotting /home/bmb/pecanGenome/orthofinder/kinfin/kinfin_results/all/all.rarefaction_curve.pdf
[STATUS] - Plotting /home/bmb/pecanGenome/orthofinder/kinfin/kinfin_results/cluster_size_distribution.pdf
Traceback (most recent call last):
  File "/home/n1806171b/biosoft/kinfin1.0.3/kinfin-1.0.3/src/kinfin.py", line 2311, in <module>
    dataFactory.write_output()
  File "/home/n1806171b/biosoft/kinfin1.0.3/kinfin-1.0.3/src/kinfin.py", line 658, in write_output
    self.write_cluster_metrics()
  File "/home/n1806171b/biosoft/kinfin1.0.3/kinfin-1.0.3/src/kinfin.py", line 937, in write_cluster_metrics
    cluster_metrics_line.append(clusterObj.protein_length_stats['mean'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```
can you give me a hand?
Thanks a lot!

I am sorry for any inconvenience caused.

cheers,

Junhao Chen

**Comment by lulahahah** [comment]
excuse me, have you solved this problem? I have the same issue as yours
